# Generated by Django 3.1.1 on 2020-10-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competitionmodel_new_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionmodel',
            old_name='users',
            new_name='players',
        ),
    ]
